language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - python setup.py install
    - python2.7 -c "import nltk; nltk.download('wordnet');"
script:
    - coverage run setup.py test
after_success:
    - coveralls
notifications:
  email:
    - msilver@csail.mit.edu
  on_failure: always
